backend/ancient_interactive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('roman_map.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/roman_map/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('api/territories/', view=views.getTerritories, name='getTerritories'),
    path('api/histories/', view=views.getHistories, name='getHistories'),
    path('api/places/', view=views.getAncientPlaces, name='getAncientPlaces'),
    path('api/custom-draws/', view=views.CustomDrawsAPIView.as_view(), name='customDraws'),
    path('api/test-questions/<int:quiz_id>/', view=views.getTestQuestions, name='getTestQuestions'),

    path('', view=views.fooldal, name='fooldal'),
    path('login/', view=views.bejelentkezes, name='bejelentkezes'),
    path('map/', view=views.terkep, name='terkep'),
    path('logout/', view=views.kijelentkezes, name='kijelentkezes'),
    path('password/', view=views.jelszovaltas, name='jelszovaltas'),
    path('user-infos/', view=views.sajatadatok, name='sajatadatok'),
    
    path('test/', views.teszt, name='teszt'),
    path('test/add-test/', view=views.uj_teszt_keszitese, name='uj_teszt_keszitese'),
    path('test/<int:quiz_id>/test-details/', view=views.teszt_reszletei, name='teszt_reszletei'),
    path("test/<int:quiz_id>/add-question/<str:question_type>/", view=views.kerdes_hozzadasa, name="kerdes_hozzadasa"),
    path('test/<int:quiz_id>/delete/', view=views.teszt_torlese, name='teszt_torlese'),
    path('test/<int:quiz_id>/test-details/<int:question_id>/', view=views.kerdes_torlese, name='kerdes_torlese'),
    path('test/run-test/<int:quiz_id>/', view=views.teszt_inditasa, name='teszt_inditasa'),
    path('tiles/<int:z>/<int:x>/<int:y>.png', view=views.serve_tile, name='serve_tile'),
    path('test/results/<int:quiz_id>/', view=views.teszteredmenyek, name='teszteredmenyek'),
    path('test/<int:quiz_id>/select-questions/', view=views.kerdes_kivalasztasa, name="kerdes_kivalasztasa"),
    

]

backend/roman_map/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_delete
from django.core.exceptions import ValidationError
from django.dispatch import receiver
import os

# Create your models here.

class CustomUser(AbstractUser):
    tanulo = models.BooleanField(default=False)
    tanar = models.BooleanField(default=False)

    def __str__(self):
        return self.last_name + ' ' + self.first_name
    

class Territorie(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=True)
    start_date = models.IntegerField()
    end_date = models.IntegerField()
    color = models.CharField(max_length=10)
    coordinates = models.TextField(blank=False)

    def save(self, *args, **kwargs):
        if self.start_date and self.end_date and self.start_date > self.end_date:
            raise ValidationError("A kezdődátum nem lehet később mint a befejezés.")
        super().save(*args, **kwargs)


    def __str__(self):
        return str(self.id)+' '+self.name+' '+str(self.start_date)+' '+str(self.end_date)

class Historie(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=True)
    description = models.TextField()
    coordinates = models.TextField(blank=True)
    HISTORIE_TYPE_CHOICHES = [
        ('csata','csata'),
        ('esemeny', 'esemény'),
    ]
    historie_type = models.CharField(max_length=255, choices=HISTORIE_TYPE_CHOICHES)
    image = models.ImageField(upload_to='historie/', default=None, blank=True)
    date = models.IntegerField(default=1000)
    

    def __str__(self):
        return str(self.id)+' '+self.name+' '+self.historie_type

@receiver(post_delete, sender=Historie)
def delete_image_file(sender, instance, **kwargs):
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

class CustomDraw(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=True)
    coordinates = models.TextField(blank=False)
    TYPE_CHOICHES = [
        ("point","Point"),
        ("linestring", "LineString"),
        ("polygon", "Polygon"),
        
    ]
    type = models.CharField(max_length=255, blank=False, choices=TYPE_CHOICHES)
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)+' '+self.name+' '+self.created_by.last_name+' '+self.created_by.first_name
    
class Quiz(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='created_quizzes', null=True, blank=True)

    def __str__(self):
        return self.title
    
class Question(models.Model):
    id = models.BigAutoField(primary_key=True)
    QUESTION_TYPES = [
        ('mc', 'Több válasz'),
        ('tf', 'Igaz/Hamis')
    ]
    def validate_positiv_number(value):
        if value < 0:
            raise ValidationError(
                ('%(value)s kisebb min 0.'),
                params={'value': value},
            )
    quiz = models.ForeignKey(Quiz, on_delete=models.SET_NULL, related_name='questions', null=True, blank=True)
    text = models.CharField(max_length=255, blank=False)
    question_type = models.CharField(max_length=2, choices=QUESTION_TYPES)
    points = models.PositiveIntegerField(default=0, validators=[validate_positiv_number])

    def __str__(self):
        return self.text
    
class Answer(models.Model):
    id = models.BigAutoField(primary_key=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField(max_length=255, blank=True)
    is_correct = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.text} ({'Correct' if self.is_correct else 'Incorrect'})"

class UserScore(models.Model):
    def validate_positiv_number(value):
        if value < 0:
            raise ValidationError(
                ('%(value)s kisebb min 0.'),
                params={'value': value},
            )
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='scores', blank=False)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=False)
    total_score = models.PositiveIntegerField(default=0, validators=[validate_positiv_number])

    def __str__(self):
        return f"{self.user} - {self.quiz.title}: {self.total_score} points"
class UserAnswer(models.Model):
    def validate_positiv_number(value):
        if value < 0:
            raise ValidationError(
                ('%(value)s kisebb min 0.'),
                params={'value': value},
            )
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='user_answers')
    selected_answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='user_selections')
    is_correct = models.BooleanField()
    points_awarded = models.PositiveIntegerField(default=0, validators=[validate_positiv_number])

    def __str__(self):
        return f"{self.user} - {self.question.text}: {'Correct' if self.is_correct else 'Incorrect'} ({self.points_awarded} points)"
    
class AncientPlaces(models.Model):
    id = models.BigAutoField(primary_key=True)
    modern_name = models.CharField(max_length=255)
    ancient_name = models.CharField(max_length=255)
    coordinates = models.CharField(max_length=100)
    

    def __str__(self):
        return f"{self.id} {self.ancient_name} {self.modern_name}"

backend/roman_map/templates/quiz/create_question.html
{% extends "quiz/test.html" %}

{% block content %}
<div class="content-create-question">
    <h2>Kérdés hozzáadása a "{{ quiz.title }}" kvízhez</h2>
    <form method="post">
        {% csrf_token %}
        
        <h3>Kérdés adatai</h3>
        {{ question_form.as_p }}

        <h3>Válaszlehetőségek</h3>
        {{ formset.management_form }}
        {% for form in formset %}
            <div class="answer-form p-2 mb-2">
                {{ form.as_p }}
            </div>
        {% endfor %}
        <div class="select-question-button-container">
            <button type="submit" class="btn btn-warning">Kérdés mentése</button>
            <a href="{% url 'teszt_reszletei' quiz.id %}" class="btn btn-warning">Vissza a kvízhez</a>
        </div>
        
    </form>

    
</div>

{% endblock %}

backend/roman_map/templates/quiz/create_test.html
{% extends "quiz/test.html" %}
{% load static %}

{% block content %}
    <div class="content">
        <form action="." method="post">
            <h3 class="page-title-h3">Új teszt létrehozása</h3>
            <div class="disz-csik"></div>
            {% csrf_token %}
            <div class="form-content">
                <div class="form-container">
                    <div>
                        <label for="">Teszt címe*</label>
                        {{ form.title }}
                    </div>
                    <div>
                        <label for="">Teszt leírása</label>
                        {{ form.description }}
                    </div>
                </div>
            </div>
            
            <div class="disz-csik"></div>
            <div id="test-home-buttons">
                <button type="submit" class="btn btn-warning">Új teszt létrehozása</button>
                <a href="{% url 'teszt' %}" class="btn btn-warning" id="panel-home-btn">
                    <span class="btn-text">Vissza a tesztekhez</span>
                </a>
            </div>
        </form>
    </div>  
{% endblock content %}

backend/roman_map/templates/quiz/run_test.html
{% extends "quiz/test.html" %}
{% block content %}
    <div class="content" id="run-test-content">
        <h2>"{{ quiz.title }}" teszt megoldása</h2>
        <p>Sok sikert a teszt megoldása során!</p>
        <div class="disz-csik"></div>
        <form method="post">
            {% csrf_token %}
            {% for question in questions %}
                <div class="question-item">
                    <p><strong>{{ forloop.counter }}. {{ question.text }}</strong></p>
                    <div class="question-item-inputs">
                        {% if question.question_type == 'tf' %}
                            <div class="form-check">
                                <input type="radio" name="question_{{ question.id }}" value="true" class="form-check-input" id="question_{{ question.id }}">
                                <label for="question_{{ question.id }}">Igaz</label>
                            </div>
                            <div class="form-check">
                                <input type="radio" name="question_{{ question.id }}" value="false" class="form-check-input" id="question_{{ question.id }}">
                                <label for="question_{{ question.id }}">Hamis</label>
                            </div> 
                        {% else %}
                            {% for answer in question.answers.all %}
                                <div class="form-check">
                                    <input type="checkbox" name="question_{{ question.id }}" value="{{ answer.id }}" class="form-check-input" id="question_{{ question.id }}">
                                    <label for="question_{{ question.id }}">{{ answer.text }}</label>
                                </div>   
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            
            <button type="submit" class="btn btn-warning">Teszt befejezése</button>
        </form>
        <div class="disz-csik"></div>
    </div>
    
{% endblock content %}

backend/roman_map/templates/quiz/select_questions.html
{% extends "quiz/test.html" %}
{% block content %}
<div class="content-select-questions">
    <h3>Kérdések hozzáadása a teszthez</h3>
    <h5>Válassza ki a teszthez hozzáadni kívánt kérdéseket!</h5>
    <form action="" method="post">
        {% csrf_token %}
        {% for question in questions %}
        <div class="select-question-container">
            <label for="{{question.id}}">{{question.text}}</label>
            <input type="checkbox" id="{{question.id}}" name="questions" value="{{question.id}}"><br>
        </div>
            
        {% endfor %}
        <div class="select-question-button-container">
            <button type="submit" class="btn btn-warning">Hozzáadás a teszthez</button>
            <a href="{% url 'teszt_reszletei' quiz.id %}" class="btn btn-warning">Mégse</a>
        </div>
        
    </form>
</div>  
{% endblock content %}

backend/roman_map/templates/quiz/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tesztek</title>
    <link rel="stylesheet" href="{% static 'styles/tests.css' %}">
    
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>

<body class= "tests-background">
    {% include "pages/messages.html" %}
    <div class="page-pattern left-pattern"></div>
        {% block content %}
            <div class="content">
                <h3>Tesztek főoldala</h3>
                
                    {% if quiz_list.count %}
                        <div class="table-responsive">
                            <table class="table sajat-table">
                                <thead class="sajat-head">
                                    <tr>
                                        <th>Teszt neve</th>
                                        <th>Leírás</th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for quiz in quiz_list %}
                                        <tr class="quiz-list" id="{{ quiz.id }}">
                                            <td class="td title-td"><p>{{ quiz.title }}</p></td>
                                            <td class="td description-td"><p>{{ quiz.description }}</p></td>
                                            <td class="td"><a href="{% url 'teszt_inditasa' quiz.id %}" class="btn btn-success">Teszt indítása</a></td>
                                            {% if user.tanar %}
                                                <td class="td"><a href="{% url 'teszt_reszletei' quiz.id %}" class="btn btn-warning">Részletek</a></td>                                            
                                                <td class="td"><a href="{% url 'teszt_torlese' quiz.id %}" onclick="return confirmDelete(event, this.href, 'Teszt');" class="btn btn-danger">Törlés</a></td>
                                                <td class="td"><a href="{% url 'teszteredmenyek' quiz.id %}" class="btn btn-info">Eredmények</a></td>
                                            {% endif %}
                                        </tr>     
                                    {% endfor %}
                                </tbody>
                                
                            </table>
                        </div>
                    {% else %}
                        <div class="bg-warning text-dark" id="nincs-teszt">
                            <p>Még nincs teszt.</p>
                            {% if user.tanar %}<p>A teszt hozzáadása gombra kattintva létrehozhat egyet!</p>{% endif %}
                        </div>
                        
                    {% endif %}
                
                
                <div id="test-home-buttons">
                    {% if user.tanar %}<a href="{% url 'uj_teszt_keszitese' %}" class="btn btn-warning hozzaadas-gomb">Teszt hozzáadása</a>{% endif %}
                    <a href="{% url 'fooldal' %}" class="btn btn-warning" id="panel-home-btn">
                        <span class="btn-text">Vissza a főoldalra</span>
                    </a>
                </div>
                
                
            
            </div>  
        {% endblock content %}
    <div class="page-pattern right-pattern"></div>
    <div id="delete-popup" class="popup-overlay">
        <div class="popup-content">
        <h3 id="delete-popup-title">Objektum törlése</h3>
        <label for="" id="delete-popup-label">Biztosan törli?</label>
        <div class="popup-buttons">
            <button type="button" id="deleteFeatureButton" class="apply-button">Törlés</button>
            <button type="button" id="closeDeletingPopup">Mégse</button>
        </div>
        </div>
    </div>
    <script type="module" src="{% static 'scripts/tests.js' %}"></script>
</body>
</html>

backend/roman_map/templates/quiz/test_chart.html
{% extends "quiz/test.html" %}
{% load static %}

{% block content %}
    <div class="test-results-page-content">
        <script src="https://d3js.org/d3.v7.min.js"></script>
        <input id="quiz_id" value = "{{quiz_id}}" type=hidden>
        <h3 class="quiz-subpage-title">A teszt kérdéseinek eredményei</h3>
        <div class="disz-csik"></div>
        <div id="chart-container">
            <h5>Legtöbb helyes választ kapó kérdések</h5>
            <svg width="800" height="600" id="top-score" class="svg-score-chart"></svg>
            <div class="disz-csik"></div>
            <h5>Legtöbb helytelen választ kapó kérdések</h5>
            <svg width="800" height="600" id="wrost-score" class="svg-score-chart"></svg>
        </div>
        <div class="disz-csik"></div>

        <div id="table-container" >
            <h5>A teszt kérdései</h5>
            <table id="table-root" class="table sajat-table">
                

            </table>
        </div>
        
        <a href="{% url "teszt" %}" class="btn btn-warning">Vissza a tesztekhez</a>
        <script type="module" src="{% static 'scripts/test_results.js' %}"></script>
    </div>
    

{% endblock content %}

backend/roman_map/templates/quiz/test_details.html
{% extends "quiz/test.html" %}

{% block content %}
<div class="content" id="quiz-details-content">
    <h3 class="quiz-subpage-title">A " {{ quiz.title }} " teszt kérdései:</h3>
    {% if questions.count %}
        <table class="table sajat-table">
            <thead class="sajat-head">
                <tr>
                    <th>Kérdés</th>
                    <th>Típus</th>
                </tr>
            </thead>
            <tbody>
                {% for question in questions %}
                    <tr>
                        <td>{{ question.text }}</td>
                        <td>({{ question.get_question_type_display }})</td>
                        <td><a href="{% url "kerdes_torlese" quiz.id question.id %}" onclick="return confirmDelete(event, this.href, 'Kérdés');" class="btn btn-warning">Törlés</a></td>
                    </tr>    
                
                {% endfor %}
            </tbody>
            
        </table>
    {% else %}
        <div>
            <p>Még nincsenek kérdések</p>
        </div>
    {% endif %}
    
    
    

    <form method="post" id="new-question-form">
        {% csrf_token %}
       
        <h4>Új kérdés létrehozása</h4>
        <label for="">{{ form.question_type.label }}</label>
        <div id="new-question-start">
            
            {{ form.question_type }}   
            <button type="submit" class="btn btn-warning">Tovább</button>
        </div>
        <div class="disz-csik"></div>
        <div id="select-and-prew-links-container">
            <a href="{% url 'kerdes_kivalasztasa' quiz.id %}" class="btn btn-warning">Kérdés hozzáadása a meglévő kérdések közzül</a>
            <a href="{% url 'teszt' %}" class="btn btn-warning">Vissza a tesztek listájához</a>
        </div>
        

        
    </form>


    
</div>

{% endblock %}

backend/roman_map/templates/quiz/test_result.html
{% extends 'quiz/test.html' %}

{% block content %}
    <div class="content">
        <h2>"{{ quiz.title }}" teszt eredménye</h2>
        <p>Elért pontszám: {{ score }} / {{ total_points }}</p>
        <a href="{% url 'teszt' %}" class="btn btn-warning">Vissza a tesztekhez</a>
    </div>
    
{% endblock %}